apiVersion: v1
kind: Service
metadata:
  name: my-app-lb
  labels:
    app: my-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80  # This is the port that the service will expose
    targetPort: 80  # This is the port that the service will forward traffic to
    protocol: TCP
  selector:
    app: nginx